# Generated by Django 3.1.1 on 2020-10-16 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('author', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('w', models.PositiveIntegerField()),
                ('h', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('page_num', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('publish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RawPageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=False)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.page')),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.publication')),
            ],
        ),
        migrations.CreateModel(
            name='RawCropData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=False)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.page')),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.publication')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.publication'),
        ),
        migrations.AddField(
            model_name='article',
            name='coordinate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coordinate'),
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.page'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.publication'),
        ),
    ]
